name: CI Checks - Kotlin Tests

on: [push, pull_request]

jobs:
  check-kotlin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Set default Rust version to stable
        run: rustup default stable

      - name: Show default version of NDK
        run: echo $ANDROID_NDK_ROOT

      - name: Run ktlintCheck on bitcoin-ffi-jvm
        run: |
          cd bitcoin-ffi-jvm
          ./gradlew ktlintCheck

      - name: Generate Kotlin JVM
        run: ./scripts/uniffi_bindgen_generate_kotlin.sh

      - name: Run bitcoin-ffi-jvm tests
        run: |
          cd bitcoin-ffi-jvm
          ./gradlew test
